export const FETCH_NEARBY_CINEMAS = 'FETCH_NEARBY_CINEMAS';
export const FETCH_NEARBY_CINEMAS_START = 'FETCH_NEARBY_CINEMAS_START';
export const FETCH_NEARBY_CINEMAS_SUCCESS = 'FETCH_NEARBY_CINEMAS_SUCCESS';
export const FETCH_NEARBY_CINEMAS_ERROR = 'FETCH_NEARBY_CINEMAS_ERROR';

export const FETCH_CINEMA_MOVIES = 'FETCH_CINEMA_MOVIES';
export const FETCH_CINEMA_MOVIES_START = 'FETCH_CINEMA_MOVIES_START';
export const FETCH_CINEMA_MOVIES_SUCCESS = 'FETCH_CINEMA_MOVIES_SUCCESS';
export const FETCH_CINEMA_MOVIES_ERROR = 'FETCH_CINEMA_MOVIES_ERROR';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_START = 'FETCH_MOVIE_DETAILS_START';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_ERROR = 'FETCH_MOVIE_DETAILS_ERROR';
